@startuml
left to right direction
actor Customer
actor BankOperator
usecase "CreateCustomer" as UC_CreateCustomer
usecase "GetCustomer" as UC_GetCustomer
usecase "UpdateCustomer" as UC_UpdateCustomer
usecase "DeleteCustomer" as UC_DeleteCustomer
usecase "AddAuthorizedSigner" as UC_AddSigner

Customer -> UC_GetCustomer
BankOperator -> UC_CreateCustomer
BankOperator -> UC_UpdateCustomer
BankOperator -> UC_DeleteCustomer
BankOperator -> UC_AddSigner
@enduml