spring.application.name=ms-customer-service
server.port=8090
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=INFO
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: bootcampbd